### ISSUE TITLE
rtems 初学者问题

### ISSUE THREAD

**Issue by 15991381612** [RTEMS/rtems-docs#4]
我是第一次学习rtems，但是我不清楚如何测试我自己的硬件开发板和编写自己的应用程序，能帮助我吗？

**Comment by gedare** [comment]
https://devel.rtems.org/wiki/GSoC/GettingStarted

**Comment by 15991381612** [comment]
我这边想使用stm32f429开发板，我想知道应该如何进行入门，我根据新手入门文档完成了Build a Board Support Package ，但是我不清楚如何进行板级支持包测试。

![image](https://user-images.githubusercontent.com/92292142/172510396-1832545e-1328-49a9-add3-5c1111fff00b.png)

**Comment by gedare** [comment]
There is no stm32f4-sis BSP. The 'sis' BSP is for a specific simulator target (https://git.rtems.org/sis/)

**Comment by 15991381612** [comment]
我查看了快速开发的文档，stm32f4构建成功，接下来我想对bsp修改，我不清楚如何修改bsp，不知道如何将我开发的程序烧录至stm32f4开发板？能帮助我一下吗？最好能图文教程

**Comment by dtbpkmte** [comment]
Maybe this blog of mine can help you: https://medium.com/@dtbpkmte/gsoc-2022-rtems-community-bonding-period-week-1-958e442f5d87

**Comment by 15991381612** [comment]
I would like to know how to add my own user application and which configuration files need to be modified. I can't do that in the introductory tutorial because I am using STM32F429
